package com.malibin.memo.util

const val CATEGORY_SAVE_RESULT_OK = 10

const val MEMO_IMPORTANT_FILTER_RESULT = 100
const val MEMO_ALL_FILTER_RESULT = 101
const val MEMO_CATEGORY_FILTER_RESULT = 102
const val MEMO_CATEGORY_SELECTED = 103

const val MEMO_DELETED = 104
const val MEMO_SAVED = 105
const val MEMO_EDIT_CANCELED = 106